name: aplikasilaporan
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.0'

dependencies: 
  cloud_firestore: ^3.1.5
  cupertino_icons: ^1.0.2
  double_back_to_close_app: ^2.1.0
  firebase_auth: ^3.3.3
  firebase_core: ^1.10.5
  get: ^4.5.1
  google_fonts: ^2.1.0
  intl: ^0.17.0
  lottie: ^1.2.1
  image_picker: 0.8.4+4
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter:
  assets:
    - assets/
  uses-material-design: true

